---
title: "Ejercicio regresión 1"
author: "Julio Sorroche"
date: "10 de enero de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r plots}
## R Markdown
DIN <- c(12,15,18,21,24,27,30,33,36)
ASA <- c(12.5,25,50,100,200,400,800,1600,3200)

movieFrame = data.frame(DIN,ASA)

rm(DIN,ASA)

colnames(movieFrame) <- c("DIN","ASA")
g_range <- range(0, movieFrame[,"DIN"], movieFrame[,"ASA"])

plot(movieFrame[,"DIN"],movieFrame[,"ASA"],type="o", col="blue",ann=FALSE,axes=FALSE,ylim=g_range)
title(main="Sensibilidad", col.main="green", font.main=2)
title(xlab="DIN", col.lab=rgb(0,0.6,0))
title(ylab="ASA", col.lab=rgb(0,0.6,0))
axis(2, las=1, at=300*0:g_range[2])


```
You,can embed an R code chunk like this:
```
```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


